export default {
  amazon: 'https://www.amazon.com/',
  menu: '#nav-hamburger-menu',
  smartHomeIcon:'#hmenu-content > ul.hmenu.hmenu-visible > li:nth-child(9) > a > i',
  homeEntertainment:'#hmenu-content > ul.hmenu.hmenu-visible.hmenu-translateX > li:nth-child(11) > a',
  televisions:'div:nth-child(1) > div > div > a > img',
  countItems: '._octopus-search-result-card_style_apbSearchResultItem__2-mx4',
  location: '#nav-main > div.nav-left > div > div > div.glow-toaster-footer > span.a-button.a-spacing-top-base.a-button-base.glow-toaster-button.glow-toaster-button-dismiss > span > input',
  todayDealsIcon: '#nav-xshop > a:nth-child(2)',
  software: 'div.GridFilters-module__gridFilterSection_36xNFAVppWfx4i4otzVc2Y > span:nth-child(3) > ul > li:nth-child(42) > label > input',
  softwareItem: '#slot-14 > #dealsGridLinkAnchor > [data-testid="grid-widget"] > #grid-main-container > .Grid-module__gridSection_1SEJTeTsU88s6aVeuuekAp > [data-testid="grid-deals-container"] > :nth-child(1) > .DealGridItem-module__dealItemContent_1vFddcq1F8pUxM8dd9FW32 > [data-testid="deal-card"] > .DealCardDynamic-module__linkOutlineOffset_2XU8RDGmNg2HG1E-ESseNq > .DealCardDynamic-module__cardImageVertical_1IizpyChuPf_yh4IHtuaWk > .a-image-container',
  softwareTitle: '#wayfinding-breadcrumbs_feature_div  span > a',
  softwareText:'Software\n            \n                Antivirus & Security\n            \n                 Antivirus',
  language: '#icp-nav-flyout > span > span.nav-line-2 > span.nav-icon.nav-arrow',
  selectCurrency:'#a-popover-1 > div > div > ul > li.a-dropdown-item.icp-currency-dropdown-disabled-option',
  currencyMenu:'#icp-currency-dropdown-selected-item-prompt > span > span',
  AED: '#icp-currency-dropdown_23 > :nth-child(1)',
  save: '#icp-save-button > span > input',
  firstItem: '.a-spacing-mini > .a-image-container > img',
  aedText: ':nth-child(2) > .a-list-item > .octopus-dlp-asin-section > .octopus-dlp-asin-info-section > .octopus-dlp-price > .a-price > [aria-hidden="true"] > .a-price-symbol',
  DDL: '#searchDropdownBox',
  electronics: '#twotabsearchtextbox',
  search: '#nav-search-submit-button',
  appleItem: '[data-component-id="6"]',
  ratting: '#acrCustomerReviewText',
  price: '#apex_desktop_renewedTier2AccordionRow > #corePrice_desktop > .a-section > .a-lineitem > tbody > tr > .a-color-secondary',
  shipping: '#apex_desktop_renewedTier2AccordionRow > #amazonGlobal_feature_div',
  stock: '#renewedTier2AccordionRow > .a-box-inner > .a-accordion-inner > :nth-child(1) > #addToCart > #renewedAccordionRowContent > :nth-child(1) > #availabilityInsideBuyBox_feature_div > :nth-child(1) > #availability > .a-size-medium',
  addToCard: '#add-to-cart-button',
  addSuccess: '#NATC_SMART_WAGON_CONF_MSG_SUCCESS',
  }